### ISSUE TITLE
卒業制作課題のレビュー

### ISSUE THREAD

**Issue by 8kjapon** [8kjapon/similar-songs#41]
# Webアプリの概要
このアプリケーションは「世の中に存在している"似ている曲"を見つけるためのプロセスを簡略化したい」という思いを込めて作成することにしました。
"似ている曲"と言っても様々で、よく似ている基準として扱われるものに音楽の"ジャンル"があります。
ただ偏にジャンルと言っても沢山あります。
更に同じジャンルだったとしても「本当に同じジャンルなのか？」と思えるほどスタイルが違う物も存在しており、さらに混乱が生じてしまいます。
そこで今回は"似ている曲"の中でも"メロディが似ている曲"を基準にすることで他には無い音楽の出会いが出来るようなサービスを目指します。
普段音楽好きでも"メロディが似ている曲"を意識して曲探しをすることはあまりありません。ただそんな"メロディが似ている曲"を見つけた時は意外にも興奮するものです。
さらに"メロディが似ている"を基準にしているのでメロディさえ似ていればジャンルなんて関係がありません。
そのため"似ているメロディ"を通して新しいジャンルと出会える機会まであります。
そんな意外で楽しい音楽との出会いが出来るのがこのサービス・アプリケーションです。

# 1週間辺りの開発に向けられる時間
- 1週間辺り: 70時間

# ProjectsのURL
[8kjapon / similar-song開発プロジェクト](https://github.com/users/8kjapon/projects/3/views/1?sumFields=%5B138729173%5D&hideItemsCount=false)

# MVPリリースまで
- [ ] Rails環境の構築と設定
- [ ] トップページ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] 楽曲登録機能
- [ ] 登録された楽曲の閲覧・検索機能
- [ ] プロフィール機能
- [ ] 楽曲への評価機能
- [ ] 公開サーバー上へのデプロイ

# MVP後
- [ ] i18n対応
- [ ] SNSログイン(Google、Twitter/X)
- [ ] レスポンシブデザインへの対応
- [ ] 細かなタグ・ジャンルカテゴリー機能の実装
- [ ] 検索機能のマルチ検索・オートコンプリート機能の対応
- [ ] 他サービスのAPIを活用した自動入力やオススメ機能の実装
- [ ] インタフェースのAjax化

# MVPレビュー依頼予定日
予定日: 2024年11月3日

**Comment by 8kjapon** [comment]
*追記
カリキュラム内でGitHubのプロジェクトURLを入力する場所に誤ったURLを入力してしまったかもしれません。
確認方法や変更方法がありましたらそちらも教えていただきたいです。

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

デプロイは仮トップページ前には行いましょう。

---

以下、MVPに含めなくても良いかもと思ったカードになります。
- プライバシーポリシー
- 利用規約
- 開発者ページ
- ログイン状況によって表示変化
- パスワード変更
- メールアドレス変更
- パスワード再設定
- マイページ

**Comment by 8kjapon** [comment]
ありがとうございます。
再度プロジェクトの調整を行いたいと思います。
