### ISSUE TITLE
MVPレビュー依頼

### ISSUE THREAD

**Issue by 8kjapon** [8kjapon/similar-songs#72]
## 各種情報
サービスの概要：似ている楽曲を閲覧、登録することのできる音楽紹介サービス
MVPで検証する事柄：サーバーの負荷、データ量やアクセス量が増えた場合に生じる問題
サービス名：musim
サービスURL：https://musim.8kjapon.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] ユーザー登録機能
- [ ] 検索機能
- [ ] 楽曲の閲覧機能
- [ ] 似ている楽曲を一覧にして紹介する機能
- [ ] 似ている楽曲の登録機能

## READMEレビュー時から変更した機能
MVP用の機能選定やissue作成時に以下の機能を除外
- [ ] マイページ機能
- [ ] プロフィール機能
- [ ] メールアドレス・パスワード変更機能
- [ ] 登録した楽曲の編集機能

### トップページ
[![Image from Gyazo](https://i.gyazo.com/69dcb55e18c510e35ae66a55a1f568a2.jpg)](https://gyazo.com/69dcb55e18c510e35ae66a55a1f568a2)

### 似てる曲の閲覧ページ
[![Image from Gyazo](https://i.gyazo.com/7fb58809b1398fc6751c2e2c08d81d90.jpg)](https://gyazo.com/7fb58809b1398fc6751c2e2c08d81d90)

### 検索ページ
[![Image from Gyazo](https://i.gyazo.com/8b1d0d5c656b4613f0cec064825d2f7b.jpg)](https://gyazo.com/8b1d0d5c656b4613f0cec064825d2f7b)

### 楽曲登録ページ
[![Image from Gyazo](https://i.gyazo.com/ff76f4fc9e4e6368b6df50f192d0ab11.jpg)](https://gyazo.com/ff76f4fc9e4e6368b6df50f192d0ab11)

### 登録ページのサジェストとオートコンプリート
[![Image from Gyazo](https://i.gyazo.com/f123035fdcdab5530208b3b865fc16e0.jpg)](https://gyazo.com/f123035fdcdab5530208b3b865fc16e0)

**Comment by busitora** [comment]
音楽登録の部分以外はいいと思いました!

以下気になった部分です。

https://musim.8kjapon.com/song_pairs/new

1. リリース年のプルダウンの初期値がなく、入力が面倒なので、初期値で2020等いれてもいいかもしれません。

Youtubeを登録しようと思いましたがエラーになりまして、投稿できませんでした。(youtubeリンクは適当です)
例: https://www.youtube.com/watch?v=ZVqJkuaLyMo&ab_channel=%E4%BB%8A%E5%8F%A4%E8%B3%80%E7%BF%94%E3%80%90%E3%83%88%E3%83%AC%E3%83%BC%E3%83%8B%E3%83%B3%E3%82%B0%E7%A7%91%E5%AD%A6%E3%80%91


2. エラーメッセージも、登録できないユーザーが理解できるようしたほうがいいかと思いました。
「Media url は有効なYouTubeリンクである必要があります」

**Comment by 8kjapon** [comment]
レビューありがとうございます。
では登録ページの修正を中心に改めて調整をしようかと思います。

## 修正点
- [ ] リリース年の入力方式と初期値
- [ ] YouTubeのリンクの取り扱いについて
- [ ] エラーメッセージの調整

**Comment by 8kjapon** [comment]
こちら https://github.com/8kjapon/similar-songs/pull/73 のプルリクエストにて上記の修正点を調整済み
以下プルリクエスト内容
> # 概要
> MVPレビュー #72 で添削のあった楽曲登録フォームの調整
> 
> # 詳細
> MVPレビューの添削ポイントである楽曲登録フォームの以下の点を調整
> 
> ## リリース年の入力方式と初期値
> * リリース年の入力方式をプルダウンメニューに変更
> * 初期値を現在の年に設定
> 
> ## YouTubeのリンクの取り扱いについて
> * 対応していなかったURL形式を把握
> * 意図しない形式のURLが入力された場合は一般的なYouTubeのURL(`https://www.youtube.com/watch?v=xxxxxxxxxxx`)に自動で整形する機能を実装
> 
> ## エラーメッセージの調整
> * エラーメッセージをi18nによる日本語化
> * 各エラーメッセージを具体的な内容に設定

**Comment by kashiwagi-rena** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

test投稿をさせていただきました。お手数ですが消していただけると幸いです

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。

**Comment by 8kjapon** [comment]
ありがとうございます。
test投稿の件、承知しました。後ほど対応したいと思います。
ではこちらでissueを閉じたいと思います。
